### ISSUE TITLE
通知が次の日に来る場合がある

### ISSUE THREAD

**Issue by nanaten** [hayabusabusa/ChukyoBustime#42]
すでに5分前を切っているバスにアラームを設定しようとするとエラーメッセージが出ますが、
そのまま次の日の同じ時間になると通知が来てしまうようです。

**Comment by hayabusabusa** [comment]
こちら #47 で対応して修正できた( はず )と思うのでクローズします🙇‍♂️  
ご報告ありがとうございましたー😄
