### ISSUE TITLE
バスの時刻表が更新されていない

### ISSUE THREAD

**Issue by dokimiki** [hayabusabusa/ChukyoBustime#81]
中京大学豊田キャンパスのバスの時刻表が変わった影響で、アプリに正しいバスの到着時間が表示されません。
おそらくFirebaseのデータを更新すれば治ると思われます。
お忙しいところ恐縮ですが、修正の方お願いできますでしょうか。
[中京大学スクールバス時刻表](https://www.chukyo-u.ac.jp/support/pdf/studentlife/bustime240425.pdf)

**Comment by hayabusabusa** [comment]
@dokimiki issue の作成ありがとうございます！反応遅くなってしまって申し訳ないです...

> 中京大学豊田キャンパスのバスの時刻表が変わった影響で、アプリに正しいバスの到着時間が表示されません。

こちら状況把握しました。
対応まで少し時間がかかってしまうかもしれませんが時刻表のデータも更新します🙇‍♂️
現状カレンダーの方しか PDF を監視できておらず、気付くのが遅くなってしまって申し訳ないです💦

報告いただけて本当に助かります！もし他にも気になる点等あればぜひ教えてくださいー

**Comment by dokimiki** [comment]
確認ありがとうございます！

ほかに不満点はありません！在校生みんなでありがたく使わせてもらっています！！

> 報告いただけて本当に助かります！もし他にも気になる点等あればぜひ教えてくださいー

こちらこそ素晴らしいアプリをありがとうございます！！

**Comment by hayabusabusa** [comment]
@dokimiki 対応が遅くなってすみません...
こちら現在公開されている時刻表のデータで更新が完了しました🙇‍♂️

- [【A'ダイヤ】祝日講義日及び【定期試験期間ダイヤ】4/25更新](https://www.chukyo-u.ac.jp/support/pdf/studentlife/bustime240425.pdf)

今後は時刻表の更新を検知できるよう、[こちらのリポジトリ](https://github.com/hayabusabusa/chukyo-bustime-observe-pdf)にて監視の仕組みを作る予定です。

今回報告いただけてすごく助かりました！
また気になるところがあれば、お気軽に issue 等で連絡いただけると嬉しいです！

**Comment by dokimiki** [comment]
お忙しい中、修正ありがとうございます！

問題が修正されたのが確認できたので、このissueはcloseさせていただきます！
